### ISSUE TITLE
borg & "forever-incremental" backups

### ISSUE THREAD

**Issue by DiagonalArg** [restic/others#21]
You have:

    borg review,dedup,encrypted,python,authenticated

I may be misunderstanding, but you want "incremental" with this, also?  Borg does so-called "forever-incremental" backups, as does bup.

Ah, I also see you have:

    bup review,dedup,incremental,error-correction

But bup can also encrypt when used with [encbuf](https://bup.github.io/).

**Comment by fd0** [comment]
In case of borg I think we can add the `incremental` tag, would you mind opening a PR?

For bup, I'm leaning towards not adding the `encryption` tag, as the script is external to bup. Otherwise I could also call `tar` an encrypting backup program when used with `gpg`.

Thanks!

**Comment by DiagonalArg** [comment]
Sorry, man.  I only use github for reporting issues.  I'm not a developer so I don't know how to do a pull request.
