### ISSUE TITLE
obnam is unmaintained

### ISSUE THREAD

**Issue by achims311** [restic/others#25]
According to this post:
https://blog.liw.fi/posts/2017/08/13/retiring_obnam/
obnam is unmaintained, or at least soon unmaintained.

**Comment by fd0** [comment]
Indeed, thanks.

**Comment by fd0** [comment]
Hm, it's already tagged as 'unmaintained'. Is there anything else we should do?

**Comment by achims311** [comment]
So, sorry I didi not notice this tag.
Closing
