### ISSUE TITLE
Tape/external media support?

### ISSUE THREAD

**Issue by tbuskey** [restic/others#26]
Some of us need offline storage.  Tapes / DVD to a safe in a different building gives disaster recovery.
Sometimes it can't be sent over the network to another server either.

**Comment by fd0** [comment]
So? What does that have to do with a list of backup programs, which this repo (`restic/others`) is about?

**Comment by fd0** [comment]
It looks like you've got the wrong repo. Maybe you meant to open this issue for the restic backup program? That would be this repo: https://github.com/restic/restic

I'm going to close this issue for now, please feel free to add further comments. Thanks!

**Comment by tbuskey** [comment]
I like the list of other backup software.  Some of them can go to tape, or DVDs or other offline media.  It'd be nice to have a flag for the ones that can.

**Comment by fd0** [comment]
Ok, I understand. Can you open a pull request which adds the tag?
