### ISSUE TITLE
Déjà Dup

### ISSUE THREAD

**Issue by harmlessdrudge** [restic/others#59]
Déjà Dup is missing from the list

https://wiki.gnome.org/Apps/DejaDup

It's a simple, easy to use wrapper for Duplicity and was once incorporated with Ubuntu. It's nothing special but the ease of use for many home users is significant. Mission: "aim to convert people who don't currently have backups into people that do."

https://www.linux.com/topic/desktop/total-system-backup-and-recall-deja-dup/ (a bit dated but ok)

I use and recommend BackInTime for backups with a GUI but it seems to be dying, which is why I checked on this one and scanned your list. My other backup tools are Borg and Timeshift.

**Comment by cfcs** [comment]
Closing because `deja-dup` is on the list under `List of wrappers or helper tools:`. It is missing tags / review though, if you submit a PR with additional tags I will merge those.
